eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
application:
  version: 1.0.0
  title: API Gateway Microservice
  author: Celestino Agudo
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
  zipkin:
    baseUrl: http://localhost:9411
server:
  port: '8083'
  error:
    include-message: always
