apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-microservice
  labels:
    app: fraud-microservice
spec:
  replicas: 1
  template:
    metadata:
      name: fraud-microservice
      labels:
        app: fraud-microservice
    spec:
      containers:
        - name: fraud-microservice
          image: celestinosdockeracct/fraud-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud-microservice