apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-microservice
  labels:
    app: customer-microservice
spec:
  replicas: 1
  template:
    metadata:
      name: customer-microservice
      labels:
        app: customer-microservice
    spec:
      containers:
        - name: customer-microservice
          image: celestinosdockeracct/customer-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer-microservice